Theorotical Questions

In [3]:
import numpy as np

ini_array = np.array([1, 2, 3, 6, 4, 5])

res = np.flip(ini_array)

print("final array", str(res))


final array [5 4 6 3 2 1]


In [2]:
import numpy as np

ini_array = np.array([1, 2, 3, 6, 4, 5])

print("initial array", str(ini_array))

print("type of ini_array", type(ini_array))

res = ini_array[::-1]

print("final array", str(res))


initial array [1 2 3 6 4 5]
type of ini_array <class 'numpy.ndarray'>
final array [5 4 6 3 2 1]


In [4]:
import numpy as np

ini_array = np.array([1, 2, 3, 6, 4, 5])

print("initial array", str(ini_array))

print("type of ini_array", type(ini_array))

res = np.flipud(ini_array)

print("final array", str(res))


initial array [1 2 3 6 4 5]
type of ini_array <class 'numpy.ndarray'>
final array [5 4 6 3 2 1]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

data_type = arr.dtype
print("Data type:", data_type)


Data type: int32


In [7]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
type(x)
x.dtype

dtype('int32')

In [8]:
x.shape

(2, 3)

In [11]:
y = x[:,1]
y
y[0] = 9 
y
x

array([[1, 9, 3],
       [4, 5, 6]])

In [15]:
#example of hstack()
import numpy as np

in_arr1 = np.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1) 

in_arr2 = np.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2) 

out_arr = np.hstack((in_arr1, in_arr2)) 
print ("Output horizontally stacked array:\n ", out_arr) 


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


In [16]:
#example of vstack()
import numpy as np

in_arr1 = np.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1) 

in_arr2 = np.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2) 

out_arr = np.vstack((in_arr1, in_arr2)) 
print ("Output vertically stacked array:\n ", out_arr) 


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
  [[1 2 3]
 [4 5 6]]


In [17]:
#example of fliplr()
import numpy as np

array = np.arange(8).reshape((2,2,2)) 
print("Original array : \n", array) 

print("\nFlipped array left-right : \n", np.fliplr(array)) 


Original array : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

Flipped array left-right : 
 [[[2 3]
  [0 1]]

 [[6 7]
  [4 5]]]


In [18]:
#example of flipud()
import numpy as np 

array = np.arange(8).reshape((2,2,2)) 
print("Original array : \n", array) 

print("\nFlipped array : \n", np.flipud(array)) 


Original array : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

Flipped array : 
 [[[4 5]
  [6 7]]

 [[0 1]
  [2 3]]]


In [19]:
import numpy as np
Arr = np.array([1, 2, 3, 4, 5, 6])
array = np.array_split(arr, 3)
print(array)


[array([1, 2]), array([3, 4]), array([5])]


In [20]:
import numpy as np 

a = np.array([5, 7, 3, 1]) 
b = np.array([90, 50, 0, 30]) 

c = a * b 
print(c) 


[450 350   0  30]


In [43]:
import numpy as np
import timeit

print(np.sum(np.arange(15000)))

print("Time taken by vectorized sum : ", end = "")
%timeit np.sum(np.arange(15000))

total = 0
for item in range(0, 15000):
	total += item
a = total
print("\n" + str(a))

print("Time taken by iterative sum : ", end = "")
%timeit a


112492500
Time taken by vectorized sum : 23.7 μs ± 3.54 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)

112492500
Time taken by iterative sum : 41.2 ns ± 11.9 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


Practical Questions

In [27]:
import numpy as np 
 
matrix = np.array([[13, 26, 33], 
                   [47, 59, 62], 
                   [79, 87, 98]]) 
 
print(matrix) 

[[13 26 33]
 [47 59 62]
 [79 87 98]]


In [28]:
matrix.T

array([[13, 47, 79],
       [26, 59, 87],
       [33, 62, 98]])

In [29]:
import numpy as np

array_1d = np.arange(10) 

array_2x5 = array_1d.reshape(2, 5)

array_5x2 = array_1d.reshape(5, 2)

print("1D Array:")
print(array_1d)
print("\n2x5 Array:")
print(array_2x5)
print("\n5x2 Array:")
print(array_5x2)


1D Array:
[0 1 2 3 4 5 6 7 8 9]

2x5 Array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [30]:
import numpy as np

array_4x4 = np.random.rand(4, 4)

array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

print("4x4 Array with Random Floats:")
print(array_4x4)
print("\n6x6 Array with Border of Zeros:")
print(array_with_border)


4x4 Array with Random Floats:
[[0.18764573 0.24174109 0.01717577 0.37090574]
 [0.73081837 0.51449918 0.57980024 0.24484041]
 [0.64240662 0.5779607  0.50352623 0.22207238]
 [0.99045969 0.02488718 0.83563179 0.28543031]]

6x6 Array with Border of Zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.18764573 0.24174109 0.01717577 0.37090574 0.        ]
 [0.         0.73081837 0.51449918 0.57980024 0.24484041 0.        ]
 [0.         0.64240662 0.5779607  0.50352623 0.22207238 0.        ]
 [0.         0.99045969 0.02488718 0.83563179 0.28543031 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [31]:
import numpy as np

array_integers = np.arange(10, 61, 5)

print("Array of Integers from 10 to 60 with a Step of 5:")
print(array_integers)


Array of Integers from 10 to 60 with a Step of 5:
[10 15 20 25 30 35 40 45 50 55 60]


In [32]:
import numpy as np

array_strings = np.array(['python', 'numpy', 'pandas'])

uppercase = np.char.upper(array_strings)
lowercase = np.char.lower(array_strings)
titlecase = np.char.title(array_strings)
capitalize = np.char.capitalize(array_strings)

print("Original Array:")
print(array_strings)
print("\nUppercase:")
print(uppercase)
print("\nLowercase:")
print(lowercase)
print("\nTitle Case:")
print(titlecase)
print("\nCapitalized:")
print(capitalize)


Original Array:
['python' 'numpy' 'pandas']

Uppercase:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase:
['python' 'numpy' 'pandas']

Title Case:
['Python' 'Numpy' 'Pandas']

Capitalized:
['Python' 'Numpy' 'Pandas']


In [33]:
import numpy as np

array_words = np.array(['hello', 'world', 'numpy', 'python'])

spaced_words = np.char.join(' ', array_words)

print("Original Array of Words:")
print(array_words)
print("\nWords with Spaces Between Characters:")
print(spaced_words)


Original Array of Words:
['hello' 'world' 'numpy' 'python']

Words with Spaces Between Characters:
['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


In [34]:
import numpy as np

array1 = np.array([[1, 2, 3], 
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9], 
                   [10, 11, 12]])

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nElement-wise Addition:")
print(addition)
print("\nElement-wise Subtraction:")
print(subtraction)
print("\nElement-wise Multiplication:")
print(multiplication)
print("\nElement-wise Division:")
print(division)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise Division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [35]:
import numpy as np

identity_matrix = np.eye(5)

diagonal_elements = np.diag(identity_matrix)

print("5x5 Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [36]:
import numpy as np

random_integers = np.random.randint(0, 1001, size=100)

def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

prime_numbers = np.array([num for num in random_integers if is_prime(num)])

print("Random Integers:")
print(random_integers)
print("\nPrime Numbers in the Array:")
print(prime_numbers)


Random Integers:
[144 305 856   6  15 992 351 762 582 186 409 329 561 714 305 420  50 205
 367 691 109 628 888  62 105 527 108 411 910 764 246 377 547 977 802  43
  25 843 611 704 175  62 937 542 299 736  91 208 305 216 915 694 127 962
 982 138   8 753  85 767 221 835 916 236 855  10 782 204 365 312  78 691
 176 668 908 818  10 707 456 163 368 828 505 428 968  93 135 220 514 213
 801 816 559 378 240 181 845   8 441 446]

Prime Numbers in the Array:
[409 367 691 109 547 977  43 937 127 691 163 181]


In [ ]:
import numpy as np

daily_temperatures = np.random.uniform(15, 30, size=30)

weekly_temperatures = daily_temperatures.reshape(4, 7)

weekly_averages = np.mean(weekly_temperatures, axis=1)

print("Daily Temperatures for a Month:")
print(daily_temperatures)
print("\nWeekly Temperatures:")
print(weekly_temperatures)
print("\nWeekly Averages:")
print(weekly_averages)
